"""Add missing tables and rename summary

Revision ID: 5ce22cfe0671
Revises: da5c6f7c3fc5
Create Date: 2026-07-14 20:45:53.963386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ce22cfe0671'
down_revision: Union[str, Sequence[str], None] = 'da5c6f7c3fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_meeting_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['tbl_meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_semantic_segment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('topic_label', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('summary_content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['tbl_meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_speaker',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('voice_sample_id', sa.UUID(), nullable=True),
    sa.Column('speaker_label', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['tbl_meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_speaker_statistic',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('speaker_id', sa.UUID(), nullable=False),
    sa.Column('total_speaking_time', sa.Float(), nullable=False),
    sa.Column('number_of_speeches', sa.Integer(), nullable=False),
    sa.Column('lively_discussion', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['tbl_meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_search_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('content_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['tbl_meeting.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['tbl_transcript_segment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tbl_summary')
    op.alter_column('tbl_transcript_segment', 'speaker_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='speaker_id::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_transcript_segment', 'speaker_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.create_table('tbl_summary',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('meeting_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['tbl_meeting.id'], name=op.f('tbl_summary_meeting_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_summary_pkey'))
    )
    op.drop_table('tbl_search_index')
    op.drop_table('tbl_speaker_statistic')
    op.drop_table('tbl_speaker')
    op.drop_table('tbl_semantic_segment')
    op.drop_table('tbl_meeting_summary')
    # ### end Alembic commands ###
