"""Add VoiceSample table

Revision ID: da5c6f7c3fc5
Revises: 
Create Date: 2026-07-14 15:41:06.882167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'da5c6f7c3fc5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_voice_sample',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('speaker_label', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('duration', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('tbl_audio_file_meeting_id_fkey'), 'tbl_audio_file', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_audio_file', 'tbl_meeting', ['meeting_id'], ['id'])
    op.drop_constraint(op.f('tbl_processing_job_meeting_id_fkey'), 'tbl_processing_job', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_processing_job', 'tbl_meeting', ['meeting_id'], ['id'])
    op.drop_constraint(op.f('tbl_processing_step_job_id_fkey'), 'tbl_processing_step', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_processing_step', 'tbl_processing_job', ['job_id'], ['id'])
    op.alter_column('tbl_summary', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('tbl_summary_meeting_id_fkey'), 'tbl_summary', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_summary', 'tbl_meeting', ['meeting_id'], ['id'])
    op.alter_column('tbl_transcript_segment', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tbl_transcript_segment', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    op.drop_constraint(op.f('tbl_transcript_segment_meeting_id_fkey'), 'tbl_transcript_segment', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_transcript_segment', 'tbl_meeting', ['meeting_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_transcript_segment', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_transcript_segment_meeting_id_fkey'), 'tbl_transcript_segment', 'tbl_meeting', ['meeting_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tbl_transcript_segment', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    op.alter_column('tbl_transcript_segment', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'tbl_summary', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_summary_meeting_id_fkey'), 'tbl_summary', 'tbl_meeting', ['meeting_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tbl_summary', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'tbl_processing_step', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_processing_step_job_id_fkey'), 'tbl_processing_step', 'tbl_processing_job', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'tbl_processing_job', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_processing_job_meeting_id_fkey'), 'tbl_processing_job', 'tbl_meeting', ['meeting_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'tbl_audio_file', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_audio_file_meeting_id_fkey'), 'tbl_audio_file', 'tbl_meeting', ['meeting_id'], ['id'], ondelete='CASCADE')
    op.drop_table('tbl_voice_sample')
    # ### end Alembic commands ###
